import streamlit as st
from enum import Enum

class Teams(Enum):
    NHL_Anaheim_Ducks = {"teamname": "Anaheim Ducks", "sportid": 3, "eventgroupid": 42133, "teamwebsite": "https://www.nhl.com/ducks/"}
    NHL_Arizona_Coyotes = {"teamname": "Arizona Coyotes", "sportid": 3, "eventgroupid": 42133, "teamwebsite": "https://www.nhl.com/coyotes/"}
    NHL_Boston_Bruins = {"teamname": "Boston Bruins", "sportid": 3, "eventgroupid": 42133, "teamwebsite": "https://www.nhl.com/bruins/"}
    NHL_Buffalo_Sabres = {"teamname": "Buffalo Sabres", "sportid": 3, "eventgroupid": 42133, "teamwebsite": "https://www.nhl.com/sabres/"}
    NHL_Calgary_Flames = {"teamname": "Calgary Flames", "sportid": 3, "eventgroupid": 42133, "teamwebsite": "https://www.nhl.com/flames/"}
    NHL_Carolina_Hurricanes = {"teamname": "Carolina Hurricanes", "sportid": 3, "eventgroupid": 42133, "teamwebsite": "https://www.nhl.com/hurricanes/"}
    NHL_Chicago_Blackhawks = {"teamname": "Chicago Blackhawks", "sportid": 3, "eventgroupid": 42133, "teamwebsite": "https://www.nhl.com/blackhawks/"}
    NHL_Colorado_Avalanche = {"teamname": "Colorado Avalanche", "sportid": 3, "eventgroupid": 42133, "teamwebsite": "https://www.nhl.com/avalanche/"}
    NHL_Columbus_Blue_Jackets = {"teamname": "Columbus Blue Jackets", "sportid": 3, "eventgroupid": 42133, "teamwebsite": "https://www.nhl.com/bluejackets/"}
    NHL_Dallas_Stars = {"teamname": "Dallas Stars", "sportid": 3, "eventgroupid": 42133, "teamwebsite": "https://www.nhl.com/stars/"}
    NHL_Detroit_Red_Wings = {"teamname": "Detroit Red Wings", "sportid": 3, "eventgroupid": 42133, "teamwebsite": "https://www.nhl.com/redwings/"}
    NHL_Edmonton_Oilers = {"teamname": "Edmonton Oilers", "sportid": 3, "eventgroupid": 42133, "teamwebsite": "https://www.nhl.com/oilers/"}
    NHL_Florida_Panthers = {"teamname": "Florida Panthers", "sportid": 3, "eventgroupid": 42133, "teamwebsite": "https://www.nhl.com/panthers/"}
    NHL_Los_Angeles_Kings = {"teamname": "Los Angeles Kings", "sportid": 3, "eventgroupid": 42133, "teamwebsite": "https://www.nhl.com/kings/"}
    NHL_Minnesota_Wild = {"teamname": "Minnesota Wild", "sportid": 3, "eventgroupid": 42133, "teamwebsite": "https://www.nhl.com/wild/"}
    NHL_Montreal_Canadiens = {"teamname": "Montreal Canadiens", "sportid": 3, "eventgroupid": 42133, "teamwebsite": "https://www.nhl.com/canadiens/"}
    NHL_Nashville_Predators = {"teamname": "Nashville Predators", "sportid": 3, "eventgroupid": 42133, "teamwebsite": "https://www.nhl.com/predators/"}
    NHL_New_Jersey_Devils = {"teamname": "New Jersey Devils", "sportid": 3, "eventgroupid": 42133, "teamwebsite": "https://www.nhl.com/devils/"}
    NHL_New_York_Islanders = {"teamname": "New York Islanders", "sportid": 3, "eventgroupid": 42133, "teamwebsite": "https://www.nhl.com/islanders/"}
    NHL_New_York_Rangers = {"teamname": "New York Rangers", "sportid": 3, "eventgroupid": 42133, "teamwebsite": "https://www.nhl.com/rangers/"}
    NHL_Ottawa_Senators = {"teamname": "Ottawa Senators", "sportid": 3, "eventgroupid": 42133, "teamwebsite": "https://www.nhl.com/senators/"}
    NHL_Philadelphia_Flyers = {"teamname": "Philadelphia Flyers", "sportid": 3, "eventgroupid": 42133, "teamwebsite": "https://www.nhl.com/flyers/"}
    NHL_Pittsburgh_Penguins = {"teamname": "Pittsburgh Penguins", "sportid": 3, "eventgroupid": 42133, "teamwebsite": "https://www.nhl.com/penguins/"}
    NHL_San_Jose_Sharks = {"teamname": "San Jose Sharks", "sportid": 3, "eventgroupid": 42133, "teamwebsite": "https://www.nhl.com/sharks/"}
    NHL_St_Louis_Blues = {"teamname": "St. Louis Blues", "sportid": 3, "eventgroupid": 42133, "teamwebsite": "https://www.nhl.com/blues/"}
    NHL_Tampa_Bay_Lightning = {"teamname": "Tampa Bay Lightning", "sportid": 3, "eventgroupid": 42133, "teamwebsite": "https://www.nhl.com/lightning/"}
    NHL_Toronto_Maple_Leafs = {"teamname": "Toronto Maple Leafs", "sportid": 3, "eventgroupid": 42133, "teamwebsite": "https://www.nhl.com/mapleleafs/"}
    NHL_Vancouver_Canucks = {"teamname": "Vancouver Canucks", "sportid": 3, "eventgroupid": 42133, "teamwebsite": "https://www.nhl.com/canucks/"}
    NHL_Vegas_Golden_Knights = {"teamname": "Vegas Golden Knights", "sportid": 3, "eventgroupid": 42133, "teamwebsite": "https://www.nhl.com/goldenknights/"}
    NHL_Washington_Capitals = {"teamname": "Washington Capitals", "sportid": 3, "eventgroupid": 42133, "teamwebsite": "https://www.nhl.com/capitals/"}
    NHL_Winnipeg_Jets = {"teamname": "Winnipeg Jets", "sportid": 3, "eventgroupid": 42133, "teamwebsite": "https://www.nhl.com/jets/"}
    NBA_Atlanta_Hawks = {"teamname": "Atlanta Hawks", "sportid": 4, "eventgroupid": 42648, "teamwebsite": "https://www.nba.com/hawks/"}
    NBA_Boston_Celtics = {"teamname": "Boston Celtics", "sportid": 4, "eventgroupid": 42648, "teamwebsite": "https://www.nba.com/celtics/"}
    NBA_Brooklyn_Nets = {"teamname": "Brooklyn Nets", "sportid": 4, "eventgroupid": 42648, "teamwebsite": "https://www.nba.com/nets/"}
    NBA_Charlotte_Hornets = {"teamname": "Charlotte Hornets", "sportid": 4, "eventgroupid": 42648, "teamwebsite": "https://www.nba.com/hornets/"}
    NBA_Chicago_Bulls = {"teamname": "Chicago Bulls", "sportid": 4, "eventgroupid": 42648, "teamwebsite": "https://www.nba.com/bulls/"}
    NBA_Cleveland_Cavaliers = {"teamname": "Cleveland Cavaliers", "sportid": 4, "eventgroupid": 42648, "teamwebsite": "https://www.nba.com/cavaliers/"}
    NBA_Dallas_Mavericks = {"teamname": "Dallas Mavericks", "sportid": 4, "eventgroupid": 42648, "teamwebsite": "https://www.nba.com/mavericks/"}
    NBA_Denver_Nuggets = {"teamname": "Denver Nuggets", "sportid": 4, "eventgroupid": 42648, "teamwebsite": "https://www.nba.com/nuggets/"}
    NBA_Detroit_Pistons = {"teamname": "Detroit Pistons", "sportid": 4, "eventgroupid": 42648, "teamwebsite": "https://www.nba.com/pistons/"}
    NBA_Golden_State_Warriors = {"teamname": "Golden State Warriors", "sportid": 4, "eventgroupid": 42648, "teamwebsite": "https://www.nba.com/warriors/"}
    NBA_Houston_Rockets = {"teamname": "Houston Rockets", "sportid": 4, "eventgroupid": 42648, "teamwebsite": "https://www.nba.com/rockets/"}
    NBA_Indiana_Pacers = {"teamname": "Indiana Pacers", "sportid": 4, "eventgroupid": 42648, "teamwebsite": "https://www.nba.com/pacers/"}
    NBA_Los_Angeles_Clippers = {"teamname": "Los Angeles Clippers", "sportid": 4, "eventgroupid": 42648, "teamwebsite": "https://www.nba.com/clippers/"}
    NBA_Los_Angeles_Lakers = {"teamname": "Los Angeles Lakers", "sportid": 4, "eventgroupid": 42648, "teamwebsite": "https://www.nba.com/lakers/"}
    NBA_Memphis_Grizzlies = {"teamname": "Memphis Grizzlies", "sportid": 4, "eventgroupid": 42648, "teamwebsite": "https://www.nba.com/grizzlies/"}
    NBA_Miami_Heat = {"teamname": "Miami Heat", "sportid": 4, "eventgroupid": 42648, "teamwebsite": "https://www.nba.com/heat/"}
    NBA_Milwaukee_Bucks = {"teamname": "Milwaukee Bucks", "sportid": 4, "eventgroupid": 42648, "teamwebsite": "https://www.nba.com/bucks/"}
    NBA_Minnesota_Timberwolves = {"teamname": "Minnesota Timberwolves", "sportid": 4, "eventgroupid": 42648, "teamwebsite": "https://www.nba.com/timberwolves/"}
    NBA_New_Orleans_Pelicans = {"teamname": "New Orleans Pelicans", "sportid": 4, "eventgroupid": 42648, "teamwebsite": "https://www.nba.com/pelicans/"}
    NBA_New_York_Knicks = {"teamname": "New York Knicks", "sportid": 4, "eventgroupid": 42648, "teamwebsite": "https://www.nba.com/knicks/"}
    NBA_Oklahoma_City_Thunder = {"teamname": "Oklahoma City Thunder", "sportid": 4, "eventgroupid": 42648, "teamwebsite": "https://www.nba.com/thunder/"}
    NBA_Orlando_Magic = {"teamname": "Orlando Magic", "sportid": 4, "eventgroupid": 42648, "teamwebsite": "https://www.nba.com/magic/"}
    NBA_Philadelphia_76ers = {"teamname": "Philadelphia 76ers", "sportid": 4, "eventgroupid": 42648, "teamwebsite": "https://www.nba.com/sixers/"}
    NBA_Phoenix_Suns = {"teamname": "Phoenix Suns", "sportid": 4, "eventgroupid": 42648, "teamwebsite": "https://www.nba.com/suns/"}
    NBA_Portland_Trail_Blazers = {"teamname": "Portland Trail Blazers", "sportid": 4, "eventgroupid": 42648, "teamwebsite": "https://www.nba.com/blazers/"}
    NBA_Sacramento_Kings = {"teamname": "Sacramento Kings", "sportid": 4, "eventgroupid": 42648, "teamwebsite": "https://www.nba.com/kings/"}
    NBA_San_Antonio_Spurs = {"teamname": "San Antonio Spurs", "sportid": 4, "eventgroupid": 42648, "teamwebsite": "https://www.nba.com/spurs/"}
    NBA_Toronto_Raptors = {"teamname": "Toronto Raptors", "sportid": 4, "eventgroupid": 42648, "teamwebsite": "https://www.nba.com/raptors/"}
    NBA_Utah_Jazz = {"teamname": "Utah Jazz", "sportid": 4, "eventgroupid": 42648, "teamwebsite": "https://www.nba.com/jazz/"}
    NBA_Washington_Wizards = {"teamname": "Washington Wizards", "sportid": 4, "eventgroupid": 42648, "teamwebsite": "https://www.nba.com/wizards/"}
    MLB_Baltimore_Orioles = {"teamname": "Baltimore Orioles", "sportid": 2, "eventgroupid": 84240, "teamwebsite": "https://www.mlb.com/orioles"}
    MLB_Boston_Red_Sox = {"teamname": "Boston Red Sox", "sportid": 2, "eventgroupid": 84240, "teamwebsite": "https://www.mlb.com/redsox"}
    MLB_New_York_Yankees = {"teamname": "New York Yankees", "sportid": 2, "eventgroupid": 84240, "teamwebsite": "https://www.mlb.com/yankees"}
    MLB_Tampa_Bay_Rays = {"teamname": "Tampa Bay Rays", "sportid": 2, "eventgroupid": 84240, "teamwebsite": "https://www.mlb.com/rays"}
    MLB_Toronto_Blue_Jays = {"teamname": "Toronto Blue Jays", "sportid": 2, "eventgroupid": 84240, "teamwebsite": "https://www.mlb.com/bluejays"}
    MLB_Chicago_White_Sox = {"teamname": "Chicago White Sox", "sportid": 2, "eventgroupid": 84240, "teamwebsite": "https://www.mlb.com/whitesox"}
    MLB_Cleveland_Guardians = {"teamname": "Cleveland Guardians", "sportid": 2, "eventgroupid": 84240, "teamwebsite": "http://www.cleguardians.com"}
    MLB_Detroit_Tigers = {"teamname": "Detroit Tigers", "sportid": 2, "eventgroupid": 84240, "teamwebsite": "https://www.mlb.com/tigers"}
    MLB_Kansas_City_Royals = {"teamname": "Kansas City Royals", "sportid": 2, "eventgroupid": 84240, "teamwebsite": "https://www.mlb.com/royals"}
    MLB_Minnesota_Twins = {"teamname": "Minnesota Twins", "sportid": 2, "eventgroupid": 84240, "teamwebsite": "https://www.mlb.com/twins"}
    MLB_Houston_Astros = {"teamname": "Houston Astros", "sportid": 2, "eventgroupid": 84240, "teamwebsite": "https://www.mlb.com/astros"}
    MLB_Los_Angeles_Angels = {"teamname": "Los Angeles Angels", "sportid": 2, "eventgroupid": 84240, "teamwebsite": "https://www.mlb.com/angels"}
    MLB_Oakland_Athletics = {"teamname": "Oakland Athletics", "sportid": 2, "eventgroupid": 84240, "teamwebsite": "https://www.mlb.com/athletics"}
    MLB_Seattle_Mariners = {"teamname": "Seattle Mariners", "sportid": 2, "eventgroupid": 84240, "teamwebsite": "https://www.mlb.com/mariners"}
    MLB_Texas_Rangers = {"teamname": "Texas Rangers", "sportid": 2, "eventgroupid": 84240, "teamwebsite": "https://www.mlb.com/rangers"}
    MLB_Atlanta_Braves = {"teamname": "Atlanta Braves", "sportid": 2, "eventgroupid": 84240, "teamwebsite": "https://www.mlb.com/braves"}
    MLB_Miami_Marlins = {"teamname": "Miami Marlins", "sportid": 2, "eventgroupid": 84240, "teamwebsite": "https://www.mlb.com/marlins"}
    MLB_New_York_Mets = {"teamname": "New York Mets", "sportid": 2, "eventgroupid": 84240, "teamwebsite": "https://www.mlb.com/mets"}
    MLB_Philadelphia_Phillies = {"teamname": "Philadelphia Phillies", "sportid": 2, "eventgroupid": 84240, "teamwebsite": "https://www.mlb.com/phillies"}
    MLB_Washington_Nationals = {"teamname": "Washington Nationals", "sportid": 2, "eventgroupid": 84240, "teamwebsite": "https://www.mlb.com/nationals"}
    MLB_Chicago_Cubs = {"teamname": "Chicago Cubs", "sportid": 2, "eventgroupid": 84240, "teamwebsite": "https://www.mlb.com/cubs"}
    MLB_Cincinnati_Reds = {"teamname": "Cincinnati Reds", "sportid": 2, "eventgroupid": 84240, "teamwebsite": "https://www.mlb.com/reds"}
    MLB_Milwaukee_Brewers = {"teamname": "Milwaukee Brewers", "sportid": 2, "eventgroupid": 84240, "teamwebsite": "https://www.mlb.com/brewers"}
    MLB_Pittsburgh_Pirates = {"teamname": "Pittsburgh Pirates", "sportid": 2, "eventgroupid": 84240, "teamwebsite": "https://www.mlb.com/pirates"}
    MLB_St_Louis_Cardinals = {"teamname": "St. Louis Cardinals", "sportid": 2, "eventgroupid": 84240, "teamwebsite": "https://www.mlb.com/cardinals"}
    MLB_Arizona_Diamondbacks = {"teamname": "Arizona Diamondbacks", "sportid": 2, "eventgroupid": 84240, "teamwebsite": "https://www.mlb.com/dbacks"}
    MLB_Colorado_Rockies = {"teamname": "Colorado Rockies", "sportid": 2, "eventgroupid": 84240, "teamwebsite": "https://www.mlb.com/rockies"}
    MLB_Los_Angeles_Dodgers = {"teamname": "Los Angeles Dodgers", "sportid": 2, "eventgroupid": 84240, "teamwebsite": "https://www.mlb.com/dodgers"}
    MLB_San_Diego_Padres = {"teamname": "San Diego Padres", "sportid": 2, "eventgroupid": 84240, "teamwebsite": "https://www.mlb.com/padres"}
    MLB_San_Francisco_Giants = {"teamname": "San Francisco Giants", "sportid": 2, "eventgroupid": 84240, "teamwebsite": "https://www.mlb.com/giants"}
    NFL_Arizona_Cardinals = {"teamname": "Arizona Cardinals", "sportid": 1, "eventgroupid": 88808, "teamwebsite": "https://www.azcardinals.com/"}
    NFL_Atlanta_Falcons = {"teamname": "Atlanta Falcons", "sportid": 1, "eventgroupid": 88808, "teamwebsite": "https://www.atlantafalcons.com/"}
    NFL_Carolina_Panthers = {"teamname": "Carolina Panthers", "sportid": 1, "eventgroupid": 88808, "teamwebsite": "https://www.panthers.com/"}
    NFL_Chicago_Bears = {"teamname": "Chicago Bears", "sportid": 1, "eventgroupid": 88808, "teamwebsite": "https://www.chicagobears.com/"}
    NFL_Dallas_Cowboys = {"teamname": "Dallas Cowboys", "sportid": 1, "eventgroupid": 88808, "teamwebsite": "https://www.dallascowboys.com/"}
    NFL_Detroit_Lions = {"teamname": "Detroit Lions", "sportid": 1, "eventgroupid": 88808, "teamwebsite": "https://www.detroitlions.com/"}
    NFL_Green_Bay_Packers = {"teamname": "Green Bay Packers", "sportid": 1, "eventgroupid": 88808, "teamwebsite": "https://www.packers.com/"}
    NFL_Los_Angeles_Rams = {"teamname": "Los Angeles Rams", "sportid": 1, "eventgroupid": 88808, "teamwebsite": "https://www.therams.com/"}
    NFL_Minnesota_Vikings = {"teamname": "Minnesota Vikings", "sportid": 1, "eventgroupid": 88808, "teamwebsite": "https://www.vikings.com/"}
    NFL_New_Orleans_Saints = {"teamname": "New Orleans Saints", "sportid": 1, "eventgroupid": 88808, "teamwebsite": "https://www.neworleanssaints.com/"}
    NFL_New_York_Giants = {"teamname": "New York Giants", "sportid": 1, "eventgroupid": 88808, "teamwebsite": "https://www.giants.com/"}
    NFL_Philadelphia_Eagles = {"teamname": "Philadelphia Eagles", "sportid": 1, "eventgroupid": 88808, "teamwebsite": "https://www.philadelphiaeagles.com/"}
    NFL_San_Francisco_49ers = {"teamname": "San Francisco 49ers", "sportid": 1, "eventgroupid": 88808, "teamwebsite": "https://www.49ers.com/"}
    NFL_Seattle_Seahawks = {"teamname": "Seattle Seahawks", "sportid": 1, "eventgroupid": 88808, "teamwebsite": "https://www.seahawks.com/"}
    NFL_Tampa_Bay_Buccaneers = {"teamname": "Tampa Bay Buccaneers", "sportid": 1, "eventgroupid": 88808, "teamwebsite": "https://www.buccaneers.com/"}
    NFL_Washington_Commanders = {"teamname": "Washington Commanders", "sportid": 1, "eventgroupid": 88808, "teamwebsite": "https://www.commanders.com/"}
    NFL_Baltimore_Ravens = {"teamname": "Baltimore Ravens", "sportid": 1, "eventgroupid": 88808, "teamwebsite": "https://www.baltimoreravens.com/"}
    NFL_Buffalo_Bills = {"teamname": "Buffalo Bills", "sportid": 1, "eventgroupid": 88808, "teamwebsite": "https://www.buffalobills.com/"}
    NFL_Cincinnati_Bengals = {"teamname": "Cincinnati Bengals", "sportid": 1, "eventgroupid": 88808, "teamwebsite": "https://www.bengals.com/"}
    NFL_Cleveland_Browns = {"teamname": "Cleveland Browns", "sportid": 1, "eventgroupid": 88808, "teamwebsite": "https://www.clevelandbrowns.com/"}
    NFL_Denver_Broncos = {"teamname": "Denver Broncos", "sportid": 1, "eventgroupid": 88808, "teamwebsite": "https://www.denverbroncos.com/"}
    NFL_Houston_Texans = {"teamname": "Houston Texans", "sportid": 1, "eventgroupid": 88808, "teamwebsite": "https://www.houstontexans.com/"}
    NFL_Indianapolis_Colts = {"teamname": "Indianapolis Colts", "sportid": 1, "eventgroupid": 88808, "teamwebsite": "https://www.colts.com/"}
    NFL_Jacksonville_Jaguars = {"teamname": "Jacksonville Jaguars", "sportid": 1, "eventgroupid": 88808, "teamwebsite": "https://www.jaguars.com/"}
    NFL_Kansas_City_Chiefs = {"teamname": "Kansas City Chiefs", "sportid": 1, "eventgroupid": 88808, "teamwebsite": "https://www.chiefs.com/"}
    NFL_Las_Vegas_Raiders = {"teamname": "Las Vegas Raiders", "sportid": 1, "eventgroupid": 88808, "teamwebsite": "https://www.raiders.com/"}
    NFL_Los_Angeles_Chargers = {"teamname": "Los Angeles Chargers", "sportid": 1, "eventgroupid": 88808, "teamwebsite": "https://www.chargers.com/"}
    NFL_Miami_Dolphins = {"teamname": "Miami Dolphins", "sportid": 1, "eventgroupid": 88808, "teamwebsite": "https://www.miamidolphins.com/"}
    NFL_New_England_Patriots = {"teamname": "New England Patriots", "sportid": 1, "eventgroupid": 88808, "teamwebsite": "https://www.patriots.com/"}
    NFL_New_York_Jets = {"teamname": "New York Jets", "sportid": 1, "eventgroupid": 88808, "teamwebsite": "https://www.newyorkjets.com/"}
    NFL_Pittsburgh_Steelers = {"teamname": "Pittsburgh Steelers", "sportid": 1, "eventgroupid": 88808, "teamwebsite": "https://www.steelers.com/"}
    NFL_Tennessee_Titans = {"teamname": "Tennessee Titans", "sportid": 1, "eventgroupid": 88808, "teamwebsite": "https://www.tennesseetitans.com/"}

def get_teams_by_sport_id(sport_id):
    team_names = [team.value['teamname'] for team in Teams if team.value['sportid'] == sport_id]
    return team_names


#print(Teams.NFL_Carolina_Panthers.value['teamwebsite'])